dist: xenial
language: node_js
git:
  submodules: false

before_install:
  - npm i -g npm
  - npm i -g firebase firebase-tools
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  # Source: https://gist.github.com/iedemam/9830045
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - npm --prefix="public/inspector-widget-vue" ci
  - npm --prefix="public/roles" ci
  - npm --prefix="firestore" ci
  - npm --prefix="config" ci

script:
  - npm --prefix="config" run build
  - echo "Building inside deployment scripts"
  - |
    if [[ $TRAVIS_BRANCH =~ ^(master)$ ]]; then
      firebase deploy --token "$FIREBASE_TOKEN"
    fi
