dist: xenial
language: node_js

before_install:
    - npm i -g npm
    - npm i -g firebase firebase-tools

install:
    - npm --prefix="functions" install
    - npm --prefix="public/inspector-widget-vue" install
    - npm --prefix="public/roles" install
    - npm --prefix="firestore" install
    - npm --prefix="config" install

script:
    - npm --prefix="config" run build
    - echo "Building inside deployment scripts"
    - if [[ $TRAVIS_BRANCH =~ ^(master)$ ]]; then
      firebase deploy --token \"$FIREBASE_TOKEN\"
      fi
